language: python
python: 3.6
compiler: gcc

env:
  global:
    - LD_LIBRARY_PATH="$HOME/ipopt/usr/lib:$LD_LIBRARY_PATH"
    - PKG_CONFIG_PATH="$HOME/ipopt/usr/lib/pkgconfig/"

cache:
  directories:
    - $HOME/ipopt

before_install:
  - sudo apt-get install gfortran liblapack-dev libblas-dev
  # coinor-libipopt-dev not working -> install manually
  - if ! [[ -f $HOME/ipopt/usr/lib/libipopt.so ]]; then
      pkgver="3.12.11" ;
      ipopt_src="$HOME/ipopt-src" ;
      ipopt_build="$HOME/ipopt-build" ;
      wget -O - "https://www.coin-or.org/download/source/Ipopt/Ipopt-${pkgver}.tgz" | tar -xzf - ;
      mv "Ipopt-${pkgver}" "$ipopt_src" ;
      for d in ASL Metis Mumps ; do pushd "${ipopt_src}/ThirdParty/${d}" && ./get.${d} && popd ; done ;
      mkdir -p "$ipopt_build" && pushd "$ipopt_build" ;
      "${ipopt_src}"/configure --prefix=/usr ;
      make ;
      PKG_CONFIG_LIBDIR="$HOME/ipopt/usr/lib/pkgconfig/" make DESTDIR="$HOME/ipopt" install ;
      popd ;
      sed -i -e "s:prefix=/usr:prefix=$HOME/ipopt/usr:" $HOME/ipopt/usr/lib/pkgconfig/ipopt.pc ;
   fi

      
addons:
  apt:
    update: true

install:
  - ./setup.py install
  - pip install scipy

script:
  - for script in examples/* ; do python "$script" || exit 1 ; done

deploy:
  provider: pypi
  user: g-braeunlich
  password: $PYPI_KEY
  distributions: sdist
  upload_docs: false
  on:
    tags: true
